name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 0
          AUTO_PUSH: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRETS }}
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update profile summary cards"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRETS }}
      - name: Debug information
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.MY_SECRETS }}"
          git remote -v
          git status
          git branch
