name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate README
        run: |
          echo "# My GitHub Stats" > README.md
          echo "" >> README.md
          echo "[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=ZONO33LHD&theme=dark&layout=compact)](https://github.com/anuraghazra/github-readme-stats)" >> README.md
          echo "[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=ZONO33LHD&repo=ZONO33LHD&theme=radical)](https://github.com/ZONO33LHD/ZONO33LHD)" >> README.md
          echo "![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=ZONO33LHD&show_icons=true&theme=dark)" >> README.md
          echo "<p align=\"left\">" >> README.md
          echo "  <img alt=\"Top Langs\" height=\"150px\" src=\"https://github-readme-stats.vercel.app/api/top-langs/?username=ZONO33LHD&layout=compact&count_private=true&show_icons=true&theme=tokyonight\" />" >> README.md
          echo "  <img alt=\"github stats\" height=\"150px\" src=\"https://github-readme-stats.vercel.app/api?username=ZONO33LHD&count_private=true&show_icons=true&theme=tokyonight\" />" >> README.md
          echo "</p>" >> README.md
          echo "[![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=ZONO33LHD&theme=dark)](https://github-readme-streak-stats.herokuapp.com/?user=ZONO33LHD&theme=dark)" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README with GitHub Stats"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
